Repository blocto/fcl-android, pull requests merged in 2022-10, with the labels that each got.

#25 Support blocto dev env
  fcl/src/main/AndroidManifest.xml
  fcl/src/main/java/com/portto/fcl/provider/blocto/Blocto.kt
  gradle.properties
  gradle/libs.versions.toml
Labels: refactoring

#26 Release 0.2.0
  gradle.properties
Labels: release

#27 Set distribution default value to false
  .github/pull_request_template.md
  .github/workflows/release.yml
Labels: enhancement
